spring:
  datasource:
    initialization-mode: always
    schema: classpath:schema.sql
  isExternalToken: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: prod
    
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true	
    
logging:
  path: log

workAreaName: 苏州维信，盐城维信，松岗
import:
  path: D:\plat_report\upload

access:
    record: false