spring:
  datasource:
    username: publish
    password: publish
    url: jdbc:mysql://192.168.0.170/ym_report_test?characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    
logging:
  level:
    com.yanmade.plat.report.dao: info
    
index.url: http://127.0.0.1/static/index.html

