
server:
  port: 8086  

spring:
  isExternalToken: true
  datasource:
    username: publish
    password: publish
    url: jdbc:mysql://192.168.0.170/ym_report?characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:  
  level:
    com.yanmade.plat.report.dao: error
    
index.url: http://192.168.0.170:8086/static/index.html
access.record: true